export const TABLE_WIDTH = 1008;
export const LOCATION_STORAGE_KEY = 'CURRENT_LOCATION';
export const MEDICAL_CONTACT_LIST = [
  'Primary care physician',
  'Psychiatrist',
  'Psychologist',
  'Nurse',
  'Neurologist',
  'OBGYN',
  'Dentist',
  'Nephrologist',
  'Internist',
  'Pediatric',
  'Behavior',
  'Analyst',
  'Optician',
  'ENT specialist',
  'Dermatologist',
  'Gastro entomologist',
  'Pulmonologist',
  'Podiatrist',
  'Oncologist',
  'Urologist',
  'Hematologist',
  'Waiver support coordinator',
];
export const FAMILY_CONTACT_LIST = [
  'Mother',
  'Father',
  'Foster parents',
  'Guardian',
  'Grandmother',
  'Grandfather',
  'Uncle',
  'Aunt',
  'Cousin',
  'Niece',
  'Nephew',
  'Family friend',
  'Friend',
  'Teacher',
  'Neighborhood friend',
  'Life skills aid',
  'Day program Other',
];